require 'mock_redis'
require_relative File.join("..", "..", "lib", "sync_to_redis.rb")

describe SyncToRedis do
  describe "#convert_to_frequency_files" do
    let(:path_to_bed) { "/clustertmp/brennecke/apps/splitting/ykex0cwl8w1m18x/dmel-all-chromosome-r5.51.noUex.win32.splitbg" }
    context "given a file in bed format" do
      it "generates a table generated by gnu uniq" do
        instance = SyncToRedis.new
        ShellCommand.should_receive(:run).with("cat /clustertmp/brennecke/apps/splitting/ykex0cwl8w1m18x/dmel-all-chromosome-r5.51.noUex.win32.splitbg | ruby -nae 'puts $F[3]' | uniq -c > /clustertmp/brennecke/apps/splitting/ykex0cwl8w1m18x/dmel-all-chromosome-r5.51.noUex.win32.uniqbg").once
        instance.convert_to_frequency_files(path_to_bed)
      end

      it "returns the path for gnu uniq table" do
        instance = SyncToRedis.new
        expect(instance.convert_to_frequency_files(path_to_bed)).to eq "/clustertmp/brennecke/apps/splitting/ykex0cwl8w1m18x/dmel-all-chromosome-r5.51.noUex.win32.uniqbg"
      end
    end
  end

  describe "#push_frequencies_to_redis" do

    let(:uniq_file) { ["1 yhet_0_32","1 yhet_4_36","1 yhet_0_32","1 yhet_7_39","3 yhet_0_32","1 yhet_6_38","3 yhet_0_32","1 yhet_20_52","2 yhet_0_32","1 yhet_8_40"] }
    it "increments the numbers of unique read names in a redis instance" do
      instance = SyncToRedis.new
      redis_connection = MockRedis.new

      instance.push_frequencies_to_redis(redis_connection, uniq_file)

      expect(redis_connection.get("yhet_0")).to eq "10"
    end
  end

  describe "#remove_frequences_from_redis" do
    let(:uniq_file) { ["1 yhet_0_32","1 yhet_4_36","1 yhet_0_32","1 yhet_7_39","3 yhet_0_32","1 yhet_6_38","3 yhet_0_32","1 yhet_20_52","2 yhet_0_32","1 yhet_8_40"] }
    it "decrements the numbers of unique read names in a redis instance" do
      instance = SyncToRedis.new
      redis_connection = MockRedis.new

      redis_connection.incrby("yhet_0", 11)
      instance.remove_frequences_from_redis(redis_connection, uniq_file)

      expect(redis_connection.get("yhet_0")).to eq "1"
    end

    it "removes an entry from redis once the frequency is smaller than zero" do
      instance = SyncToRedis.new
      redis_connection = MockRedis.new

      redis_connection.incrby("yhet_0", 5)
      instance.remove_frequences_from_redis(redis_connection, uniq_file)

      expect(redis_connection.exists("yhet_0")).to eq false
    end
  end
end
